name: Python Syntax Check and Merge
on:
  push:
    branches:
      - main
      - muhammad

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' # specify your preferred Python version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check Python syntax
      run: |
        find . -name "*.py" | xargs python -m py_compile
    - name: Merge to main
      if: github.ref == 'refs/heads/dev'
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Merge dev branch to main'
        branch: main
